### PR TITLE
refactor docs file

### PR DESCRIPTION
**Pull request by wrac4242**
Refactor Docs file 
if no issues with code is found before it gets merged, it will mark 1.0.0

### CODE REVIEW

**Review by Eliiia — CHANGES_REQUESTED** [review]
looks coolio so far, however a few little nitpicks:
- README doesnt have the .md extension?
- why plan.md? why not a github project board?
- ive never seen `example.env`, always `.env.example`
- i personally always seperate my imports (or in this case, require()s) by empty lines to make it slightly more readable; i put important libraries first, then other libraries, then self-created code files, then local files
feel free to ignore all of the above; they are just nitpicks, after all

the important stuff:
- if your API is mostly communicating through JSON, itd make a lot more sense to send error messages in a JSON object. you want to either do something like `res.status(404).send();` or `res.status(404).send({ error: "Not Found" });`
- Your docs page says that ALL bodies should be JSON; and on the next line you imply that any data sent should go through a JSON body. If I'm not misunderstanding this, why are you using urlencoding?

looks good for the rest tho, i think

**Comment by wrac4242** [comment]
i was going to make a point about README being githubs default, but I looked and yea that's not working, so will go through now

**Comment by wrac4242** [comment]
for the Plan.md instead of a project board, that's currently my personal preference, however, I will switch to that soon
other changes will be done soon, mainly around reordering of imports, however, I prefer not to separate them by new lines, maybe each section separated but not each import. files get too large.

**Comment by wrac4242** [comment]
please rereview, and nitpick away

**Comment by Eliiia** [comment]
oh shit yeah i didnt mean seperate each import, i meant by category yeah, will take a look again

**Review by Eliiia — CHANGES_REQUESTED** [review]
- lines 31, 34, 47, 59, and 60 in `docs.md` have an extra space
- at the starts of `notesController.js` and `tilesController.js`, why `var`? why not `let` or `const`?
- Line 31 of index.js uses apostrophes rather than ", which doesnt fit the look of your code; if youre using prettier, you can create a `.prettierrc.json` to control a few settings, including what to use for strings

looks fine apart from that

**Comment by wrac4242** [comment]
changes should be in place

**Review by Eliiia — APPROVED** [review]

**Pull request merged**
